function D = Treatment(t,tc,td,dc,dd,lam1,lam2)
    D =  dc*( exp(-lam1*(t-tc(1))).*heaviside(t-tc(1)) ...
                       + exp(-lam1*(t-tc(2))).*heaviside(t-tc(2)) ...
                       + exp(-lam1*(t-tc(3))).*heaviside(t-tc(3)) ...
                       + exp(-lam1*(t-tc(4))).*heaviside(t-tc(4)) ...
                       + exp(-lam1*(t-tc(5))).*heaviside(t-tc(5)))...
                + dd*( exp(-lam2*(t-td(1))).*heaviside(t-td(1)) ...
                       + exp(-lam2*(t-td(2))).*heaviside(t-td(2)) ...
                       + exp(-lam2*(t-td(3))).*heaviside(t-td(3)));
end